
export const Films=[
    {   
        id:"harry-potter-and-the-sorcerer-stone",
        Image: "asset/img/HarryPotter1.jpg" ,
        Banner:"../../asset/img/HarryPotter2.jpg",
        Title: "Harry Potter and the Sorcerer's Stone",
        Year: "2001",
        Nation: "USA",
        Description:"An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.",
        Rating:"4",
        FullDescription:"This is the tale of Harry Potter (Daniel Radcliffe), an ordinary eleven-year-old boy serving as a sort of slave for his aunt and uncle who learns that he is actually a wizard and has been invited to attend the Hogwarts School for Witchcraft and Wizardry. Harry is snatched away from his mundane existence by Rubeus Hagrid (Robbie Coltrane), the groundskeeper for Hogwarts, and quickly thrown into a world completely foreign to both him and the viewer. Famous for an incident that happened at his birth, Harry makes friends easily at his new school. He soon finds, however, that the wizarding world is far more dangerous for him than he would have imagined, and he quickly learns that not all wizards are ones to be trusted.",
        previously:"0",
        trailer:"https://www.youtube.com/watch?v=VyHV0BRtdxo&pp=ygUWaGFycnkgcG90dGVyIDEgdHJhaWxlcg%3D%3D",
    },

    {
        id:"no-country-for-old-man",
        Image: "asset/img/No-Country-For-Old-Men.jpg" ,
        Banner:"../../asset/img/No-Country-For-Old-Men.webp",
        Title: "No Country for Old Man",
        Year: "2007",
        Nation: "USA",
        Description:"The film follows three main characters: Llewelyn Moss, a Vietnam War veteran and welder who stumbles upon a large sum of money in the desert; Anton Chigurh, a hitman who is sent to recover the money and Ed Tom Bell, a sheriff investigating the crime.",
        Rating:"5",
        FullDescription:"In rural Texas, welder and hunter Llewelyn Moss (Josh Brolin) discovers the remains of several drug runners who have all killed each other in an exchange gone violently wrong. Rather than report the discovery to the police, Moss decides to simply take the two million dollars present for himself. This puts the psychopathic killer, Anton Chigurh (Javier Bardem), on his trail as he dispassionately murders nearly every rival, bystander and even employer in his pursuit of his quarry and the money. As Moss desperately attempts to keep one step ahead, the blood from this hunt begins to flow behind him with relentlessly growing intensity as Chigurh closes in. Meanwhile, the laconic Sheriff Ed Tom Bell (Tommy Lee Jones) blithely oversees the investigation even as he struggles to face the sheer enormity of the crimes he is attempting to thwart.",
        previously:"0",
        trailer:"https://www.youtube.com/watch?v=38A__WT3-o0&pp=ygUebm8gY291bnRyeSBmb3Igb2xkIG1lbiB0cmFpbGVy",
    },

    {
        id:"breaking-bad",
        Image: "asset/img/Breaking-Bad.webp" ,
        Banner:"../../asset/img/Breaking-Bad.jpg",
        Title: "Breaking Bad",
        Year: "2008",
        Nation: "USA",
        Description:"Set in Albuquerque, New Mexico, between 2008 and 2010, Breaking Bad follows Walter White, a struggling, frustrated high school chemistry teacher who transforms into a ruthless kingpin in the local methamphetamine drug trade, driven to financially provide for his family after being diagnosed with inoperable lung cancer.",
        Rating:"5",
        FullDescription:"A struggling high school chemistry teacher, Walter White (Bryan Cranston), is diagnosed with inoperable, advanced lung cancer. On a ride along with his DEA agent brother-in-law Hank Schrader (Dean Norris), Walter sees a former student of his, Jesse Pinkman (Aaron Paul), fleeing the scene of a meth lab. He later contacts Jesse and devises a scheme to become partners in an attempt to combine their skills to manufacture and distribute methamphetamine, with Walter cooking the product and Jesse using his street connections to distribute it. Walter says he wants to provide financial stability for his pregnant wife, Skyler (Anna Gunn) and disabled son, and to pay for his expensive cancer treatment. During Walter and Jesse's first days of selling Albuquerque's finest meth, they encounter a series of problems with local drug dealers. Walter takes to selling the meth he produces to a local druglord, Tuco Salamanca (Raymond Cruz), using the alias 'Heisenberg'.",
        previously:"0",
        trailer:"https://www.youtube.com/watch?v=HhesaQXLuRY&pp=ygUdYnJlYWtpbmcgYmFkIHNlYXNvbiAxIHRyYWlsZXI%3D",
    },

    {
        id:"7-samurai",
        Image: "asset/img/7-Samurai_.jpg" ,
        Banner:"../../asset/img/7-Samurai2.jpg",
        Title: "7 Samurai",
        Year: "1954",
        Nation: "Japan",
        Description:"Seven Samurai is set at the end of the 16th century and centres on an impoverished Japanese village that is at the mercy of a marauding gang of bandits. The bandits have ransacked the village before, stealing its crops, but, before striking again, they decide to wait until the next harvest is complete.",
        Rating:"4",
        FullDescription:"In the Sixteenth Century, in Japan, a poor village is frequently looted by armed bandits losing their crop of rice. Their patriarch Grandpa advises the villagers to hire a Ronin to defend their village. Four farmers head to town to seek out their possible protectors, but they just can offer three meals of rice per day and lodging for the samurai. They succeed in hiring the warming-hearted veteran Kambei Shimada that advises that they need six other samurai to protect their lands. Kambei recruits the necessary five samurai and the brave jester Kikuchiyo and move to the village. After a feared reception, Kambei plots a defense strategy and the samurai start training the farmers how to defend their lands and families for the battle that approaches.",
        previously:"0",
        trailer:"https://www.youtube.com/watch?v=wJ1TOratCTo&pp=ygURNyBzYW11cmFpIHRyYWlsZXI%3D",
    },
    {
        id:"old-boy",
        Image: "asset/img/Oldboy.jpg" ,
        Banner:"../../asset/img/Oldboy2.jpg",
        Title: "Old Boy",
        Year: "2003",
        Nation: "Korean",
        Description:"A loose adaptation of the Japanese manga of the same name, the film follows the story of Oh Dae-su, who is imprisoned in a cell which resembles a hotel room for 15 years without knowing the identity of his captor nor his captor's motives.",
        Rating:"5",
        FullDescription:"Oh Dae-Su, an obnoxious drunk abducted on a rainy night in 1988, wakes up in a strange, windowless hotel room. Kept under lock and key for an unknown reason, Oh Dae-Su's invisible captors keep him fed and systematically sedated to avert suicide, providing only a colour television to keep him company. And after fifteen long years in captivity, perplexed Oh Dae-Su finds himself released. Now, his pitiless abductors encourage Oh Dae-Su to track down the ones behind the mysterious kidnapping and finally get his brutal, longed-for revenge on the unknown tormentor. However, who would hate Oh Dae-Su so much that he would deny him a quick and clean death?",
        previously:"0",
        trailer:"https://www.youtube.com/watch?v=tAaBkFChaRg&pp=ygUOb2xkYm95IHRyYWlsZXI%3D",
    },
    {
        id:"saving-private-ryan",
        Image: "asset/img/Saving-Private-Ryan.jpg" ,
        Banner:"../../asset/img/Saving-Private-Ryan-2.webp",
        Title: "Saving Private Ryan",
        Year: "1998",
        Nation: "USA",
        Description:"Set in 1944 in France during World War II, it follows a group of soldiers, led by Captain John Miller, on their mission to extricate Private James Ryan from the war after his three brothers are killed in battle.",
        Rating:"5",
        FullDescription:"Opening with the Allied invasion of Normandy on 6 June 1944, members of the 2nd Ranger Battalion under Cpt. Miller fight ashore to secure a beachhead. Amidst the fighting, two brothers are killed in action. Earlier in New Guinea, a third brother is KIA. Their mother, Mrs. Ryan, is to receive all three of the grave telegrams on the same day. The United States Army Chief of Staff, George C. Marshall, is given an opportunity to alleviate some of her grief when he learns of a fourth brother, Private James Ryan, and decides to send out 8 men (Cpt. Miller and select members from 2nd Rangers) to find him and bring him back home to his mother...",
        previously:"0",
        trailer:"https://www.youtube.com/watch?v=9CiW_DgxCnQ&pp=ygUbc2F2aW5nIHByaXZhdGUgcnlhbiB0cmFpbGVy",
    },
    {
        id:"better call saul",
        Image: "asset/img/Better-Call-Saul.jpg" ,
        Banner:"../../asset/img/Better-Call-Saul2.jpg",
        Title: "Better Call Saul",
        Year: "2015",
        Nation: "USA",
        Description:"Better Call Saul follows the transformation of Jimmy McGill, a former con artist who is trying to become a respectable lawyer, into the personality of the flamboyant criminal lawyer Saul Goodman",
        Rating:"5",
        FullDescription:"Before he met Walter White, Saul Goodman was struggling working-class lawyer Jimmy McGill. How did McGill become Mr. Goodman and what led him to his life with the notorious 'Heisenberg' in the first place? 'Better Call Saul' is the origin story of a man trying to survive in a harsh, exploitative world where anyone and everyone will try and take him, and his dreams, down.",
        previously:"0",
        trailer:"https://www.youtube.com/watch?v=9q4qzYrHVmI&pp=ygUhYmV0dGVyIGNhbGwgc2F1bCBzZWFzb24gMSB0cmFpbGVy",
    },
    {
        id:"puss-in-boots-last-wish",
        Image: "asset/img/Puss-in-Boots.jpg" ,
        Banner:"../../asset/img/Puss-in-Force2.jpg",
        Title: "Puss in Boots: Last Wish",
        Year: "2022",
        Nation: "USA",
        Description:"When Puss in Boots discovers that his passion for adventure has taken its toll and he has burned through eight of his nine lives, he launches an epic journey to restore them by finding the mythical Last Wish.",
        Rating:"5",
        FullDescription:"Sadly, Puss in Boots, the undaunted Spanish lover and hero, is now down to the last of his nine lives, a decade after the events of Mèo Đi Hia (2011). And as if that weren't enough, the unstoppable bounty hunter known as The Big Bad Wolf is after him. To restore all of his precious lives and escape an inglorious fate, Puss must pluck up his courage to embark on a dangerous quest into the Dark Forest to find the legendary Wishing Star. However, Puss isn't the only one seeking the map to the magical star. As the daring outlaw puts his skills to good use to stay one step ahead of formidable adversaries determined to get their hands on it, a crucial question arises: Does he have what it takes to face his most skilled and terrifying opponent and get his life back on track?",
        previously:"0",
        trailer:"https://www.youtube.com/watch?v=RqrXhwS33yc&pp=ygUjcHVzcyBpbiBib290cyB0aGUgbGFzdCB3aXNoIHRyYWlsZXI%3D",
    },
    {
        id:"3-idiots",
        Image: "asset/img/3-idiots.jpg" ,
        Banner:"../../asset/img/3-idiots-2.jpg",
        Title: "3 Idiots",
        Year: "2009",
        Nation: "India",
        Description:"Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them 'idiots'.",
        Rating:"5",
        FullDescription:"3 Idiots is a Bollywood production that flashes back and forth between present day, and the characters' time in college. It starts off with old friends, Qureshi and Raju Rastogi learning that their college pal, Rancho, had finally been found. The movie follows their travels to find their long lost friend, while flashing back to the events of their school years, where they often got into amusing shenanigans involving the Dean of Delhi's Imperial College of Engineering, Viru Sahastrabudhe, and dealt with some serious events that many people encounter in every day life.",
        previously:"0",
        trailer:"https://www.youtube.com/watch?v=xvszmNXdM4w&pp=ygUQMyBpZGlvdHMgdHJhaWxlcg%3D%3D",
    },
    {
        id:"hacksaw-ridge",
        Image:"asset/img/Hacksaw-Ridge.jpg",
        Banner:"../../asset/img/Hacksaw-Ridge.jpg",
        Title:"HackSaw Ridge",
        Year:"2016",
        Description:"World War II American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first man in American history to receive the Medal of Honor without firing a shot.",
        Rating:"5",
        FullDescription:"An American army veteran grieves by the tombstones of his army company that died during World War I. Back home, he raises his sons in a pious setting and asks them to shun weapons. After a naughty fight turns awry, Desmond reads the Bible and vows not to harm another human in his life thereafter. Desmond then saves the life of a worker, experiencing a wholesome satisfaction in the process. In the hospital, he is smitten by a nurse, who he then dates. After the United States enters the Second World War, both sons enlist, adding to the ire of the father who despises his sons joining the Army. The rigorous regimen of training in the Army requires Desmond to clear his firearms training, but after a huge tiff with his seniors, his father, an old corporal, intervenes to save Desmond from being court-martialed and serve with the Army as a medic. They get posted to Hacksaw Ridge, Okinawa. A win there would ensure that the Empire of Japan surrenders to the Allied Forces. What happens thereon?",
        previously:"1",
        trailer:"https://www.youtube.com/watch?v=s2-1hz1juBI&pp=ygUVaGFja3NhdyByaWRnZSB0cmFpbGVy",
    },

    {
        id:"blair-witch-project",
        Image:"asset/img/Blair-Witch-Project.png",
        Banner:"../../asset/img/Blair-Witch-Project.png",
        Title:"Blair Witch Project",
        Year:"1999",
        Description:"The film purports to be footage found in the discarded cameras of three young filmmakers who had gone missing. In October 1994, film students Heather, Mike, and Josh set out to produce a documentary about the mythical Blair Witch. They travel to Burkittsville, Maryland, and interview residents about the myth.",
        Rating:"3",
        FullDescription:"In search of a local legend, three bold amateur documentarians--director, Heather; cameraman, Josh; sound recorder, Mike--hike into Burkittsville's gloomy Black Hills Forest to find a shadow: the fabled Blair Witch. Now, one long year later--after that fateful October of 1994--there's still no sign of the student filmmakers, apart from the raw footage they left behind. Who knows what truly happened during their creepy five-day journey into the mouth of madness? Was there, indeed, an intangible supernatural presence in the dark woods that led to the team's disappearance? Either way, the missing trio must have seen something. Could the nightmarish myth be real?",
        previously:"1",
        trailer:"https://www.youtube.com/watch?v=MBZ-POVsrlI&pp=ygUbYmxhaXIgd2l0Y2ggcHJvamVjdCB0cmFpbGVy",
    },

    {
        id:"neon-genesis-evangelion",
        Image:"asset/img/Neon-Genesis-Evangelion.jpg",
        Banner:"../../asset/img/Neon-Genesis-Evangelion.jpg",
        Title:"Neon Genesis Evangelion",
        Year:"1995",
        Description:"The series explores the experiences and emotions of Evangelion pilots and members of Nerv as they try to prevent Angels from causing more cataclysms. In the process, they are called upon to understand the ultimate causes of events and the motives for human action.",
        Rating:"3",
        FullDescription:"In 2015, 15 years after the enormous catastrophe that killed half of the world population, another crisis has come - the unidentified invaders called 'Angels' begin to attack human-kind. Any of their weapons are useless against the so-called 'Absolute Terror Field'. But now human-kind had created an exception;the ultimate all-purpose humanoid weapon 'Evangelion'. To operate this exception needs the minds of 'Children', 14-year-old juveniles. Shinji Ikari, the only son of the commander-in-chief of the team that administered Evangelion, is selected as the third of the 'Children'...!",
        previously:"1",
        trailer:"https://www.youtube.com/watch?v=-32JEJJLrzg&pp=ygUnbmVvbiBnZW5lc2lzIGV2YW5nZWxpb24gdHJhaWxlciB0diBzcG90",
    },
]

export const Images=[
    {id: '0', src: 'asset/img/Suicide-Squad.jpg'},
    {id: '1',src: 'asset/img/The-Thing.jpg'},
    {id: '2',src: 'asset/img/Gravity-Falls.jpg'},
    {id: '3',src: 'asset/img/Cowboy-Bebop.jpg'},
]